#!/usr/bin/env bash


source ./scripts/sources/helper_functions

REQS_FILE=${1:-"./whisk/requirements.txt"}
SETUP_FILE=${2:-"./whisk/setup-venv"}

if ! grep -q "gitpython" "$REQS_FILE"; then
    echo "gitpython==3.1.50; python_version > '3.7'" >> "${REQS_FILE}"
fi

pip3 install --user virtualenv --break-system-packages
sed -i -e 's/python3 -m venv "venv"/python3 -m virtualenv "venv"/g' "${SETUP_FILE}"
./whisk/setup-venv
source whisk/venv/bin/activate


if [ ! -d "./build" ]; then
    mkdir build
fi

export OE_BUILD_DIR=$(pwd)/build
export PYREX_BIND="${OE_BUILD_DIR}"

TARGET_BUILD_MODE=$(user_input "build mode" "development" "production")
TARGET_PRODUCT=$(user_input "target product" "raspberrypi3" "raspberrypi4" "raspberrypi5")
TARGET_IMAGE=$(user_input "target image version" "scarthgap" "styhead" "wrynose" )

echo "Selected ${TARGET_PRODUCT} with ${TARGET_BUILD_MODE} image of ${TARGET_IMAGE}"

git submodule set-branch --branch "${TARGET_IMAGE}" layers/open-source/poky

. ./init-build-env --product "${TARGET_PRODUCT}" --mode "${TARGET_BUILD_MODE}" --version "${TARGET_IMAGE}" --build-dir "${OE_BUILD_DIR}"
