#!/usr/bin/env bash

# This file is to be sourced to set values for the name and git URL for the various base layers

declare -A LAYER_LIST

# Open Source Layers
LAYER_LIST["open-source/poky"]="https://git.yoctoproject.org/poky.git"
LAYER_LIST["open-source/meta-raspberrypi"]="https://git.yoctoproject.org/meta-raspberrypi.git"
LAYER_LIST["open-source/meta-openembedded"]="git@github.com:openembedded/meta-openembedded.git"
LAYER_LIST["open-source/meta-arm"]="https://git.yoctoproject.org/meta-arm.git"
LAYER_LIST["open-source/meta-security"]="https://git.yoctoproject.org/meta-security.git"
LAYER_LIST["open-source/meta-swupdate"]="git@github.com:sbabic/meta-swupdate.git"
LAYER_LIST["open-source/meta-virtualization"]="https://git.yoctoproject.org/meta-virtualization.git"
LAYER_LIST["open-source/meta-secure-core"]="git@github.com:Wind-River/meta-secure-core.git"

# My Layers to be added to the build in ./commmon/
LAYER_LIST["common/meta-raspberrypi-tcook"]="git@github.com:ruaine83/meta-raspberrypi-tcook.git"
